"""Stock dataset registrations: STOCK_DAILY, STOCK_INDEX_WEIGHT, STOCK_BASIC."""

from datahub.core.dataset import Dataset, DatasetMeta, DatasetRegistry, FetchStep

# STOCK_DAILY: 股票日线数据 - 6步管道
DatasetRegistry.register(
    DatasetMeta(
        dataset=Dataset.STOCK_DAILY,
        domain="stock",
        partition_by="date",
        key_columns=["ts_code", "trade_date"],
        storage_path="stock/daily",
        date_column="trade_date",
        code_column="ts_code",
        partition_key_template="{date}",
        description="股票日线行情数据（含基本信息、每日指标、复权因子、资金流向、融资融券）",
    ),
    pipeline=[
        # Step 1: 基础日线行情
        FetchStep(
            api_name="daily",
            param_mapping={"trade_date": "date"},
            fields=None,  # 返回所有字段
            merge_on=["ts_code"],
        ),
        # Step 2: 基本信息合并
        FetchStep(
            api_name="stock_basic",
            param_mapping={},
            fixed_params={
                "exchange": "",
                "list_status": "L",
            },
            fields=["ts_code", "name", "area", "industry", "market", "list_date"],
            merge_on=["ts_code"],
            optional=True,
        ),
        # Step 3: 每日指标合并 (daily_basic)
        FetchStep(
            api_name="daily_basic",
            param_mapping={"trade_date": "date"},
            fields=[
                "ts_code",
                "trade_date",
                "close",              # 收盘价
                "turnover_rate",      # 换手率(%)
                "turnover_rate_f",    # 换手率(自由流通股)(%)
                "volume_ratio",       # 量比
                "pe",                 # 市盈率
                "pe_ttm",             # 市盈率(TTM)
                "pb",                 # 市净率
                "ps",                 # 市销率
                "ps_ttm",             # 市销率(TTM)
                "dv_ratio",           # 股息率(%)
                "dv_ttm",             # 股息率(TTM)(%)
                "total_share",        # 总股本(万股)
                "float_share",        # 流通股本(万股)
                "free_share",         # 自由流通股本(万股)
                "total_mv",           # 总市值(万元)
                "circ_mv",            # 流通市值(万元)
            ],
            merge_on=["ts_code", "trade_date"],
            optional=True,
        ),
        # Step 4: 复权因子合并
        FetchStep(
            api_name="adj_factor",
            param_mapping={"trade_date": "date"},
            fields=["ts_code", "trade_date", "adj_factor"],
            merge_on=["ts_code", "trade_date"],
            optional=True,
        ),
        # Step 5: 资金流向合并
        FetchStep(
            api_name="moneyflow",
            param_mapping={"trade_date": "date"},
            fields=[
                "ts_code",
                "trade_date",
                "buy_sm_vol",
                "buy_sm_amount",
                "sell_sm_vol",
                "sell_sm_amount",
                "buy_md_vol",
                "buy_md_amount",
                "sell_md_vol",
                "sell_md_amount",
                "buy_lg_vol",
                "buy_lg_amount",
                "sell_lg_vol",
                "sell_lg_amount",
                "buy_elg_vol",
                "buy_elg_amount",
                "sell_elg_vol",
                "sell_elg_amount",
                "net_mf_vol",
                "net_mf_amount",
            ],
            merge_on=["ts_code", "trade_date"],
            optional=True,
        ),
        # Step 6: 融资融券合并
        FetchStep(
            api_name="margin_detail",
            param_mapping={"trade_date": "date"},
            fields=[
                "ts_code",
                "trade_date",
                "rzye",
                "rqye",
                "rzmre",
                "rqyl",
                "rzche",
                "rqchl",
                "rqmcl",
                "rzrqye",
            ],
            merge_on=["ts_code", "trade_date"],
            optional=True,
        ),
    ],
)

# STOCK_INDEX_WEIGHT: 指数成分股权重 - 单步管道
DatasetRegistry.register(
    DatasetMeta(
        dataset=Dataset.STOCK_INDEX_WEIGHT,
        domain="stock",
        partition_by="composite",
        key_columns=["index_code", "con_code", "trade_date"],
        storage_path="stock/index_weight",
        date_column="trade_date",
        code_column="con_code",
        partition_key_template="{index_code}_{date}",
        description="指数成分股权重数据",
    ),
    pipeline=[
        FetchStep(
            api_name="index_weight",
            param_mapping={"trade_date": "date", "index_code": "index_code"},
            fields=None,
            merge_on=[],
        ),
    ],
)

# STOCK_BASIC: 股票基本信息列表快照 - 单步管道
DatasetRegistry.register(
    DatasetMeta(
        dataset=Dataset.STOCK_BASIC,
        domain="stock",
        partition_by="none",
        key_columns=["ts_code"],
        storage_path="stock/basic",
        date_column="",
        code_column="ts_code",
        partition_key_template="basic",
        description="股票基本信息列表",
    ),
    pipeline=[
        FetchStep(
            api_name="stock_basic",
            param_mapping={},
            fixed_params={
                "exchange": "",
                "list_status": "L",
            },
            fields=["ts_code", "symbol", "name", "area", "industry", "market", "list_date"],
            merge_on=[],
        ),
    ],
)

# STOCK_VALUATION: 股票估值指标 - 单步管道
DatasetRegistry.register(
    DatasetMeta(
        dataset=Dataset.STOCK_VALUATION,
        domain="stock",
        partition_by="date",
        key_columns=["ts_code", "trade_date"],
        storage_path="stock/valuation",
        date_column="trade_date",
        code_column="ts_code",
        partition_key_template="{date}",
        description="股票估值指标（PE/PB/PS/股息率/量比/换手率/市值）",
    ),
    pipeline=[
        FetchStep(
            api_name="daily_basic",
            param_mapping={"trade_date": "date"},
            fields=[
                "ts_code",
                "trade_date",
                "close",              # 收盘价
                "turnover_rate",      # 换手率(%)
                "turnover_rate_f",    # 换手率(自由流通股)(%)
                "volume_ratio",       # 量比
                "pe",                 # 市盈率
                "pe_ttm",             # 市盈率(TTM)
                "pb",                 # 市净率
                "ps",                 # 市销率
                "ps_ttm",             # 市销率(TTM)
                "dv_ratio",           # 股息率(%)
                "dv_ttm",             # 股息率(TTM)(%)
                "total_mv",           # 总市值(万元)
                "circ_mv",            # 流通市值(万元)
            ],
            merge_on=[],
        ),
    ],
)

# STOCK_HOLDER: 股东信息 - 单步管道
DatasetRegistry.register(
    DatasetMeta(
        dataset=Dataset.STOCK_HOLDER,
        domain="stock",
        partition_by="date",
        key_columns=["ts_code", "ann_date"],
        storage_path="stock/holder",
        date_column="ann_date",
        code_column="ts_code",
        partition_key_template="{date}",
        description="股东信息（十大流通股东）",
    ),
    pipeline=[
        FetchStep(
            api_name="top10_floatholders",
            param_mapping={"period": "date"},
            fields=["ts_code", "ann_date", "end_date", "holder_name", "hold_amount", "hold_ratio"],
            merge_on=[],
        ),
    ],
)

# STOCK_FINANCIALS_INCOME: 利润表
DatasetRegistry.register(
    DatasetMeta(
        dataset=Dataset.STOCK_FINANCIALS_INCOME,
        domain="stock",
        partition_by="date",
        key_columns=["ts_code", "end_date"],
        storage_path="stock/financials/income",
        date_column="ann_date",
        code_column="ts_code",
        partition_key_template="{date}",
        description="利润表（营收/净利润/扣非净利润等）",
    ),
    pipeline=[
        FetchStep(
            api_name="income",
            param_mapping={"ts_code": "code", "start_date": "start_date", "end_date": "end_date"},
            fields=[
                "ts_code",
                "ann_date",
                "f_ann_date",
                "end_date",
                "report_type",
                "comp_type",
                "end_type",
                "basic_eps",
                "diluted_eps",
                "total_revenue",
                "revenue",
                "int_income",
                "prem_earned",
                "comm_income",
                "n_commis_income",
                "n_oth_income",
                "n_oth_b_income",
                "prem_income",
                "out_prem",
                "une_prem_reser",
                "reins_income",
                "n_sec_tb_income",
                "n_sec_udb_income",
                "n_asset_mg_income",
                "oth_b_income",
                "fv_value_chg_gain",
                "invest_income",
                "ass_invest_income",
                "forex_gain",
                "total_cogs",
                "oper_cost",
                "int_exp",
                "comm_exp",
                "biz_tax_surchg",
                "sell_exp",
                "admin_exp",
                "fin_exp",
                "assets_impair_loss",
                "prem_refund",
                "compens_payout",
                "reser_insur_liab",
                "div_payt",
                "reins_exp",
                "oper_exp",
                "compens_payout_refu",
                "insur_reser_refu",
                "reins_cost_refund",
                "other_bus_cost",
                "operate_profit",
                "non_oper_income",
                "non_oper_exp",
                "nca_disploss",
                "total_profit",
                "income_tax",
                "n_income",
                "n_income_attr_p",
                "minority_gain",
                "oth_compr_income",
                "t_compr_income",
                "compr_inc_attr_p",
                "compr_inc_attr_m_s",
                "ebit",
                "ebitda",
                "insurance_exp",
                "undist_profit",
                "distable_profit",
                "rd_exp",
                "fin_exp_int_exp",
                "cip_other",
                "oth_oper_income",
                "interst_income",
                "taxes_and_surcharges",
                "less_operating_cost",
                "oper_profit_1",
                "update_flag",
            ],
            merge_on=[],
            optional=True,
        ),
    ],
)

# STOCK_FINANCIALS_BALANCE: 资产负债表
DatasetRegistry.register(
    DatasetMeta(
        dataset=Dataset.STOCK_FINANCIALS_BALANCE,
        domain="stock",
        partition_by="date",
        key_columns=["ts_code", "end_date"],
        storage_path="stock/financials/balance",
        date_column="ann_date",
        code_column="ts_code",
        partition_key_template="{date}",
        description="资产负债表（总资产/总负债/净资产等）",
    ),
    pipeline=[
        FetchStep(
            api_name="balancesheet",
            param_mapping={"ts_code": "code", "start_date": "start_date", "end_date": "end_date"},
            fields=[
                "ts_code",
                "ann_date",
                "f_ann_date",
                "end_date",
                "report_type",
                "comp_type",
                "end_type",
                "total_share",
                "cap_rese",
                "undistr_porfit",
                "surplus_rese",
                "special_rese",
                "money_cap",
                "trad_asset",
                "notes_receiv",
                "accounts_receiv",
                "oth_receiv",
                "prepayment",
                "div_receiv",
                "int_receiv",
                "inventories",
                "amor_exp",
                "nca_within_1y",
                "sett_rsrv",
                "loanto_oth_bank_fi",
                "premium_receiv",
                "reinsur_receiv",
                "reinsur_res_receiv",
                "pur_resale_fa",
                "oth_cur_assets",
                "total_cur_assets",
                "fa_avail_for_sale",
                "htm_invest",
                "lt_eqt_invest",
                "invest_real_estate",
                "time_deposits",
                "oth_assets",
                "lt_rec",
                "fix_assets",
                "cip",
                "oth_fix_assets",
                "goodwill",
                "lt_amor_exp",
                "defer_tax_assets",
                "decr_in_disbur",
                "oth_nca",
                "total_nca",
                "cash_reser_cb",
                "depos_in_oth_bfi",
                "prec_metals",
                "deriv_assets",
                "rr_reins_une_prem",
                "rr_reins_outstd_cla",
                "rr_reins_lins_liab",
                "rr_reins_lthins_liab",
                "refund_depos",
                "ph_pledge_loans",
                "refund_cap_depos",
                "indep_acct_assets",
                "client_depos",
                "client_prov",
                "transac_seat_fee",
                "invest_as_receiv",
                "total_assets",
                "lt_borr",
                "st_borr",
                "cb_borr",
                "depos_ib_deposits",
                "loan_oth_bank",
                "trading_fl",
                "notes_payable",
                "acct_payable",
                "adv_receipts",
                "sold_for_repur_fa",
                "comm_payable",
                "payroll_payable",
                "taxes_payable",
                "int_payable",
                "div_payable",
                "oth_payable",
                "acc_exp",
                "deferred_inc",
                "st_bonds_payable",
                "payable_to_reinsurer",
                "rsrv_insur_cont",
                "acting_trading_sec",
                "acting_uw_sec",
                "non_cur_liab_due_1y",
                "oth_cur_liab",
                "total_cur_liab",
                "bond_payable",
                "lt_payable",
                "specific_payables",
                "estimated_liab",
                "defer_tax_liab",
                "defer_inc_non_cur_liab",
                "oth_ncl",
                "total_ncl",
                "depos_oth_bfi",
                "deriv_liab",
                "depos",
                "agency_bus_liab",
                "oth_liab",
                "prem_receiv_adv",
                "depos_received",
                "ph_invest",
                "reser_une_prem",
                "reser_outstd_claims",
                "reser_lins_liab",
                "reser_lthins_liab",
                "indep_acct_liab",
                "pledge_borr",
                "indem_payable",
                "policy_div_payable",
                "total_liab",
                "treasury_share",
                "ordin_risk_reser",
                "forex_differ",
                "invest_loss_unconf",
                "minority_int",
                "total_hldr_eqy_exc_min_int",
                "total_hldr_eqy_inc_min_int",
                "total_equity",
                "total_liab_hldr_eqy",
                "lt_payroll_payable",
                "oth_comp_income",
                "oth_eqt_tools",
                "oth_eqt_tools_p_shr",
                "lending_funds",
                "acc_receivable",
                "st_fin_payable",
                "payables",
                "hfs_assets",
                "hfs_sales",
                "cost_fin_assets",
                "fair_value_fin_assets",
                "cip_total",
                "oth_pay_total",
                "long_pay_total",
                "debt_invest",
                "oth_debt_invest",
                "oth_eq_invest",
                "oth_illiq_fin_assets",
                "oth_eq_ppbond",
                "receiv_financing",
                "use_right_assets",
                "lease_liab",
                "contract_assets",
                "contract_liab",
                "accounts_receiv_bill",
                "accounts_pay",
                "oth_rcv_total",
                "fix_assets_total",
                "update_flag",
            ],
            merge_on=[],
            optional=True,
        ),
    ],
)

# STOCK_FINANCIALS_CASHFLOW: 现金流量表
DatasetRegistry.register(
    DatasetMeta(
        dataset=Dataset.STOCK_FINANCIALS_CASHFLOW,
        domain="stock",
        partition_by="date",
        key_columns=["ts_code", "end_date"],
        storage_path="stock/financials/cashflow",
        date_column="ann_date",
        code_column="ts_code",
        partition_key_template="{date}",
        description="现金流量表（经营/投资/筹资现金流）",
    ),
    pipeline=[
        FetchStep(
            api_name="cashflow",
            param_mapping={"ts_code": "code", "start_date": "start_date", "end_date": "end_date"},
            fields=[
                "ts_code",
                "ann_date",
                "f_ann_date",
                "end_date",
                "comp_type",
                "report_type",
                "end_type",
                "net_profit",
                "finan_exp",
                "c_fr_sale_sg",
                "recp_tax_rends",
                "n_depos_incr_fi",
                "n_incr_loans_cb",
                "n_inc_borr_oth_fi",
                "prem_fr_orig_contr",
                "n_incr_insured_dep",
                "n_reinsur_prem",
                "n_incr_disp_tfa",
                "ifc_cash_incr",
                "n_incr_disp_faas",
                "n_incr_loans_oth_bank",
                "n_cap_incr_repur",
                "c_fr_oth_operate_a",
                "c_inf_fr_operate_a",
                "c_paid_goods_s",
                "c_paid_to_for_empl",
                "c_paid_for_taxes",
                "n_incr_clt_loan_adv",
                "n_incr_dep_cbob",
                "c_pay_claims_orig_inco",
                "pay_handling_chrg",
                "pay_comm_insur_plcy",
                "oth_cash_pay_oper_act",
                "st_cash_out_act",
                "n_cashflow_act",
                "oth_recp_ral_inv_act",
                "c_disp_withdrwl_invest",
                "c_recp_return_invest",
                "n_recp_disp_finan_assets",
                "c_recp_return_invest_2",
                "c_recp_disp_sobu",
                "stot_inflows_inv_act",
                "c_pay_acq_const_finan_assets",
                "c_paid_invest",
                "n_disp_subs_oth_biz",
                "oth_pay_ral_inv_act",
                "n_incr_pledge_loan",
                "stot_out_inv_act",
                "n_cashflow_inv_act",
                "c_recp_borrow",
                "proc_issue_bonds",
                "oth_cash_recp_ral_fnc_act",
                "stot_cash_in_fnc_act",
                "free_cashflow",
                "c_prepay_amt_borr",
                "c_pay_dist_dpcp_int_exp",
                "incl_dvd_profit_paid_sc_ms",
                "oth_cashpay_ral_fnc_act",
                "stot_cashout_fnc_act",
                "n_cash_flows_fnc_act",
                "eff_fx_flu_cash",
                "n_incr_cash_cash_equ",
                "c_cash_equ_beg_period",
                "c_cash_equ_end_period",
                "c_recp_cap_contrib",
                "incl_cash_rec_saims",
                "uncon_invest_loss",
                "prov_depr_assets",
                "depr_fa_coga_dpba",
                "amort_intang_assets",
                "lt_amort_deferred_exp",
                "decr_deferred_exp",
                "incr_acc_exp",
                "loss_disp_finan_assets",
                "loss_scr_fa",
                "loss_fv_chg",
                "invest_loss",
                "decr_def_inc_tax_assets",
                "incr_def_inc_tax_liab",
                "decr_inventories",
                "decr_oper_receiv",
                "incr_oper_payable",
                "others",
                "im_n_cashflow_act",
                "conv_debt_into_cap",
                "conv_copyrigths_into_cap",
                "fa_fnc_leases",
                "end_bal_cash",
                "beg_bal_cash",
                "end_bal_cash_equ",
                "beg_bal_cash_equ",
                "im_n_incr_cash_equ",
                "update_flag",
            ],
            merge_on=[],
            optional=True,
        ),
    ],
)

# STOCK_DIVIDEND: 分红送股
DatasetRegistry.register(
    DatasetMeta(
        dataset=Dataset.STOCK_DIVIDEND,
        domain="stock",
        partition_by="date",
        key_columns=["ts_code", "end_date"],
        storage_path="stock/dividend",
        date_column="ann_date",
        code_column="ts_code",
        partition_key_template="{date}",
        description="分红送股（每股股息/送股/转股比例）",
    ),
    pipeline=[
        FetchStep(
            api_name="dividend",
            param_mapping={"ts_code": "code"},
            fields=[
                "ts_code",
                "end_date",
                "ann_date",
                "div_proc",
                "stk_div",
                "stk_bo_rate",
                "stk_co_rate",
                "cash_div",
                "cash_div_tax",
                "record_date",
                "ex_date",
                "pay_date",
                "div_listdate",
                "imp_ann_date",
                "base_date",
                "base_share",
            ],
            merge_on=[],
            optional=True,
        ),
    ],
)

# STOCK_REPURCHASE: 股票回购
DatasetRegistry.register(
    DatasetMeta(
        dataset=Dataset.STOCK_REPURCHASE,
        domain="stock",
        partition_by="date",
        key_columns=["ts_code", "ann_date"],
        storage_path="stock/repurchase",
        date_column="ann_date",
        code_column="ts_code",
        partition_key_template="{date}",
        description="股票回购计划及进度",
    ),
    pipeline=[
        FetchStep(
            api_name="repurchase",
            param_mapping={"start_date": "start_date", "end_date": "end_date"},
            fields=[
                "ts_code",
                "ann_date",
                "end_date",
                "proc",
                "exp_date",
                "vol",
                "amount",
                "high_limit",
                "low_limit",
            ],
            merge_on=[],
            optional=True,
        ),
    ],
)

# STOCK_PLEDGE: 股权质押统计
DatasetRegistry.register(
    DatasetMeta(
        dataset=Dataset.STOCK_PLEDGE,
        domain="stock",
        partition_by="date",
        key_columns=["ts_code"],
        storage_path="stock/pledge",
        date_column="end_date",
        code_column="ts_code",
        partition_key_template="{date}",
        description="股权质押统计（质押比例/质押金额）",
    ),
    pipeline=[
        FetchStep(
            api_name="pledge_stat",
            param_mapping={"ts_code": "code"},
            fields=[
                "ts_code",
                "end_date",
                "pledge_count",
                "unrest_pledge",
                "rest_pledge",
                "total_share",
                "pledge_ratio",
            ],
            merge_on=[],
            optional=True,
        ),
    ],
)

# STOCK_MARGIN: 融资融券明细
DatasetRegistry.register(
    DatasetMeta(
        dataset=Dataset.STOCK_MARGIN,
        domain="stock",
        partition_by="date",
        key_columns=["ts_code", "trade_date"],
        storage_path="stock/margin",
        date_column="trade_date",
        code_column="ts_code",
        partition_key_template="{date}",
        description="融资融券明细（融资余额/融券余量）",
    ),
    pipeline=[
        FetchStep(
            api_name="margin_detail",
            param_mapping={
                "trade_date": "date",
                "start_date": "start_date",
                "end_date": "end_date",
            },
            fields=[
                "ts_code",
                "trade_date",
                "rzye",
                "rqye",
                "rzmre",
                "rqyl",
                "rzche",
                "rqchl",
                "rqmcl",
                "rzrqye",
            ],
            merge_on=[],
            optional=True,
        ),
    ],
)

# TRADE_CALENDAR: 交易日历 - 基础数据
DatasetRegistry.register(
    DatasetMeta(
        dataset=Dataset.TRADE_CALENDAR,
        domain="stock",
        partition_by="date",
        key_columns=["cal_date"],
        storage_path="stock/trade_calendar",
        date_column="cal_date",
        code_column="",
        partition_key_template="{date}",
        description="交易日历（是否交易日/上/下个交易日）",
    ),
    pipeline=[
        FetchStep(
            api_name="trade_cal",
            param_mapping={"start_date": "start_date", "end_date": "end_date"},
            fixed_params={"exchange": "SSE"},
            fields=["exchange", "cal_date", "is_open", "pretrade_date"],
            optional=True,
        ),
    ],
)
